### ISSUE TITLE
Hello from cs-wasm

### ISSUE THREAD

**Issue by jonathanvdc** [RyanLamansky/dotnet-webassembly#1]
Hi there!

I stumbled across this repository and I thought you might be interested in [`cs-wasm`](https://github.com/jonathanvdc/cs-wasm), which is a C# library I wrote that basically does the same thing as `dotnet-webassembly`. At the moment, it can read, inspect, modify and write binary WebAssembly files.

Anyway, I'm curious about your motivations for creating `dotnet-webassembly`. Do you have a specific purpose in mind? Or are you just writing a WebAssembly reader/writer for the fun of it? Personally, I'm planning on using `cs-wasm` for a compiler back-end.

Thanks for reading.

**Comment by RyanLamansky** [comment]
Thanks for visiting 🙂

My long-term intention is to build a .NET Standard library that can JIT-compile WASM files.  There's enough similarity between WASM and CIL that it seems like it might not be overly difficult to do.

I've already written code to read/modify/write WASM, but it's a very rough prototype.  I'm cleaning it up and putting it here as I go.  Work on the execution process will immediately follow.

I'm not getting paid to do this, so it will take a long time 🙂

**Comment by jonathanvdc** [comment]
So you want to JIT-compile WASM to CIL? That's awesome! It'd be great to have a WASM JIT that can be embedded in .NET programs.

I'm looking forward to seeing your project evolve. :)

**Comment by RyanLamansky** [comment]
I've added a [README](https://github.com/RyanLamansky/dotnet-webassembly/blob/master/README.md) to hopefully clarify everything.

As of now, this library should be able to parse any valid WASM file, including all instructions.  I don't have a large selection of WASMs to test against, but it's able to fully parse the old AngryBots13.wasm file, a 10 MB WebGL Unity game.
