### ISSUE TITLE
Imports for Table and Global need to be supported

### ISSUE THREAD

**Issue by NicolasDorier** [RyanLamansky/dotnet-webassembly#11]
Because this is not supported, I still can't use run this [wasm library](https://aois.blob.core.windows.net/public/secp256k1.wasm).

I need to make a sample JS page using secp256k1 to help @RyanLamansky to support it.

**Comment by RyanLamansky** [comment]
Globals are in and I've started working on tables.  The main barrier there is the JavaScript API used with tables is different than the other import types: the imported table object behavior actually changes after being imported, it's not read-only.  It also binds that instance of the import to a specific instance of the compiled WebAssembly, a characteristic unique to table imports.  The way this library handles imports is not at all designed for this pattern, so I have to consider what changes I might have to make to my import strategy to work well with this, or if I should abandon my goal of being relatively similar to the JavaScript API.

**Comment by RyanLamansky** [comment]
I've given it a lot of thought and there isn't a not-terrible way to make table imports work well with the current API.  I've started on a refactoring of the compiler internals and API to be more similar to the WebAssembly JavaScript API, which should resolve the remaining feature gaps.  This will take a while.

**Comment by NicolasDorier** [comment]
No worry, let me know when you want I give another try.

**Comment by NicolasDorier** [comment]
@RyanLamansky I will close this issue, as I managed to get something working thanks to @ericsink (https://ericsink.com/entries/wasm_wasi_dotnet.html)

The solution is basically to build with clang and wasi. 
Secp256k1 is a very simple library with no dependency, so by compiling with wasi, all imports could be resolved.

You can find my binary https://aois.blob.core.windows.net/public/libsecp256k1.wasm

And my repo to reproduce the build on https://github.com/NicolasDorier/NBitcoin.Secp256k1

The library is successfully parsed by your library.

**Comment by NicolasDorier** [comment]
Just for info here:
I managed to limit my library tothe following import:

```
  (import "env" "__indirect_function_table" (table (;0;) 4 funcref))
  (import "env" "__stack_pointer" (global (;0;) (mut i32)))
  (import "env" "__memory_base" (global (;1;) i32))
  (import "env" "__table_base" (global (;2;) i32))
```
Note that there seem to have a table. So I was surprised to see that I could parse the wasm with your library, but it somehow works.

**Comment by NicolasDorier** [comment]
@RyanLamansky can you tell me why it works? [wasm](https://aois.blob.core.windows.net/public/libsecp256k1.wasm), [wat](https://aois.blob.core.windows.net/public/libsecp256k1.wat).

Despite the fact that there is this `__indirect_function_table` import table, your library does not seem to care at all.

```csharp
static void Main(string[] args)
{
    var module = Module.ReadFromBinary(@"C:\Sources\NBitcoin.Secp256k1\bin\lib\libsecp256k1.wasm");
    System.Console.WriteLine("Exports:");
    foreach(var export in module.Exports)
    {
        Console.WriteLine(export.Name);
    }
    System.Console.WriteLine("Imports:");
    foreach(var import in module.Imports)
    {
        Console.WriteLine(import.Field);
    }
}
```
Just works fine.

**Comment by RyanLamansky** [comment]
The module reader has 100% spec compliance, it's only the compiler that can't deal with imported tables.

**Comment by NicolasDorier** [comment]
Reopening as indeed the compiler is not happy.

**Comment by RyanLamansky** [comment]
I have a plan for a fix, which unfortunately requires me to rewrite a big chunk of the compiler and make breaking changes.

The current design essentially bakes all imports into the compiled DLL.  This is great for performance, but requires everything to be public + static.  This is not compatible with tables, blocks linking WebAssembly files to each other, and works differently than the JavaScript API.

To solve all of that I have to move imports to run-time using delegates.  This means the compiler needs to track the delegates associated with imports and wrap all calls to them so the delegate reference is provided as the first parameter.

I'm not sure how long this will take but I can't think of any technical blockers.  The upside of this effort is that, when done, the non-preview 1.0 release should be close behind.

**Comment by NicolasDorier** [comment]
Cool, please ping me again when you want me to test on my own library, I will give another try.

**Comment by RyanLamansky** [comment]
Version 0.5.0 has the basic features of table importing support in place.  It's good enough for the MDN sample at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Table , which is highly encouraging, but it still has a couple limitations that may or may not affect you: if the table's initial size is too small, it won't auto grow; no table exports, functions added to a table prior to importing won't be accessible if they don't have a signature that matches an internally-added entry.

Let me know if the new version works better for you.  The above shortcomings won't take me long to fix, I just ran out of weekend free time to work on this.

**Comment by NicolasDorier** [comment]
coool! I will have a look thanks a lot!

**Comment by RyanLamansky** [comment]
Version 0.6.0 fixes the shortcomings I mentioned in my last comment.  So... that means the original topic of this bug is done.  It also means that the core "MVP" feature set is all there, apart from a ton of testing needed to ensure that I did everything correctly.

I hope it works well for your library!
