### ISSUE TITLE
Is it technical feasible to run Blazor?

### ISSUE THREAD

**Issue by meteorsnows** [RyanLamansky/dotnet-webassembly#14]
Is it technical feasible to run [Blazor?](https://dotnet.microsoft.com/apps/aspnet/web-apps/client)

**Comment by RyanLamansky** [comment]
Once the last few compiler features are finished, yes.  I can't think of a reason you'd _need_ to do this (you're talking about compiling .NET code to web assembly... then running that web assembly on .NET), but it would be an interesting achievement.
