### ISSUE TITLE
Consider fixing runtime errors with EOS WASMs

### ISSUE THREAD

**Issue by pavel-gavr** [RyanLamansky/dotnet-webassembly#16]
We got three minimal WASMs which cause runtime errors with dotnet-webassembly. 
1. Don't know how to parse opcode 239
2. Instruction sequence reader ended after readering 14 characters, expected 12
3. Stream ended unexpectedly
Are you considering fixing them?
[SmallestWasmsWithDiffExceptions.zip](https://github.com/RyanLamansky/dotnet-webassembly/files/3486619/SmallestWasmsWithDiffExceptions.zip)

**Comment by RyanLamansky** [comment]
Thanks for the report!  I'll take a look in the next couple of days.

**Comment by RyanLamansky** [comment]
None of these files will load in Chrome, so I have to conclude that they're not valid WASMs.
