### ISSUE TITLE
Generate Classes From .wasm File

### ISSUE THREAD

**Issue by JasonBock** [RyanLamansky/dotnet-webassembly#22]
When you call `Compile.FromBinary<>()`, you need to specify an abstract class to represent the methods within the WebAssembly module. (Yes, I know you can use `dynamic` but I'd rather not :) ). It would be cool if there was something that would examine the module and emit a class for you so you don't have to create that yourself. Maybe something along the lines of what the Grpc packages do by automatically generating the class files needed based on the .proto files in the project. Or, just a helper method you can run once, get the class file, and then use that from now on.

**Comment by RyanLamansky** [comment]
I assume you want C# classes specifically?  My intention is to keep the core WebAssembly.dll language neutral but this is a good idea for an add-on of some kind.

Using `Module.ReadFromBinary`, you get full inspection capability of a WASM file and can generate C# code from there.

**Comment by galvesribeiro** [comment]
That would be cool to use Roslyn and Source Generators to generate the invokers for those types and would avoid all the reflection required at runtime.

**Comment by JasonBock** [comment]
@galvesribeiro that is a **very** intriguing idea. @RyanLamansky I may just submit a PR on this in the near future :)

**Comment by galvesribeiro** [comment]
Yeah, it would be nice for Orleans community if our Actors could be implemented on another languages for the sake of leveraging existent/legacy components and bring other stacks bridged by dotnet-webassembly.

We already use Roslyn and Source Generators in the project to generate serializers and some RPC method invokers and adding this to the table would definitively expand our horizons so we would bridge Actor calls to the other stacks in a transparent way by using webassembly.

**Comment by RyanLamansky** [comment]
I'm hoping to avoid adding any new dependencies on the core library, so a source generator would be a separate project. Maybe even a separate repo?

I was thinking about adding something in the Examples collection that produces an abstract class to implement for a given WASM, but I'll wait a few days see what @JasonBock comes up with.

**Comment by JasonBock** [comment]
Understood about the "new dependencies" point. I may just make my own repo and see what I come up with. Don't know when I'll do this....all depends on when the spirit is moved and all that :)

**Comment by JasonBock** [comment]
Well, I tried a couple of things this morning, and I hit some stumbling blocks....

* Source generator libraries need to target .NET Standard 2.0. `WebAssembly` targets .NET Core 3.1, so I can't reference that assembly. I could change my library to target `netcoreapp3.1`....maybe that will work.
* The bigger problem is I didn't realize that `Compile.FromBinary()` would need to actually load the wasm file in the source generator to determine what methods are exported and build an appropriate abstract type. This....may be difficult to pull off, especially if what's being passed in is a `Stream` or a `string` variable and not a constant.

I'll need to muse over these things....maybe I restrict this to `<AdditionalFiles>` and generate the types based on `.wasm` files that find there.

**Comment by RyanLamansky** [comment]
@JasonBock You can use `Module.ReadFromBinary` to get all the metadata of a WASM file and go from there. There are only 4 primitive types (int32, int64, float32, float64) and a few others for things like import/export of memory.

Bringing back .NET Standard 2.0 support could be painful due to lack of nullable types and API differences from .NET Core 3.1... I hope you're able to work around this 🤞

**Comment by JasonBock** [comment]
@RyanLamansky yeah, the plan now is to use `Module.ReadFromBinary()`. I'll have to do with an `AdditionalFile` project reference, that's the only reliable way to get the location of a file in a source generator.

Since source generators are a .NET 5.0-only thing, I don't have a lot of hope this will work targeting `.netcoreapp3.1`, but we'll find out.

**Comment by JasonBock** [comment]
@RyanLamansky well....unfortunately I can't get it to work. I'm having success getting the generator to work in a unit test scenario, but when I reference the project as an "analyzer" project from a .NET 5.0 project, I get this error:

```
CS8032, An instance of analyzer WebAssembly.Generators.WasmTypeGenerator cannot be created from C:\Users\jason\source\repos\WebAssembly.Generators\src\WebAssembly.Generators\bin\Debug\netcoreapp3.1\WebAssembly.Generators.dll : Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

I'm guessing because I had to make the generator project a .NET Core 3.1 project, it won't work correctly from a .NET 5.0 project.

BTW to quote from the folks at MS [on this topic](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/#can-i-change-the-tfm-in-a-source-generator)...

> Source Generators are .NET Standard 2.0 components, and like any project you can change the TFM. However, they only support being loaded into consuming projects as .NET Standard 2.0 components today.

I'll keep looking, but....is there any way to make `WebAssembly` target .NET Standard 2.0 as well? You mentioned you had some issues trying that before - what specifically were the issues?

**Comment by RyanLamansky** [comment]
> I'll keep looking, but....is there any way to make `WebAssembly` target .NET Standard 2.0 as well? You mentioned you had some issues trying that before - what specifically were the issues?

@JasonBock version 0.9.0-preview is the last one to have .NET Standard 2.0 support. `Module.ReadFromBinary` is virtually unchanged since then, so as long as you don't need the compiler, it may work...

**Comment by JasonBock** [comment]
@RyanLamansky unfortunately that isn't working either. I'm not sure why, but now the project that references the generator project is giving an error, trying to load `WebAssembly` as `1.0.0.0`, **even though** I don't reference `WebAssembly` anywhere now other than as `0.9.0-preview`. Frankly, I don't know if this is an issue with that version targeting both NS 2.0 and NS 2.1, or something odd with my project setup, or some bizarre issue that I can't figure out.

Not really sure where to go from this point....I'm going to try a couple more things, but if I can't figure it out I'll post this to the dotnet Discord site and see if others have any insight.

**Comment by JasonBock** [comment]
Well....building from the command line and creating an entirely new solution gives the same problem. So....I'm going to publish my solution to GitHub and post the problem to Discord. Maybe someone knows what's going on.

**Comment by JasonBock** [comment]
I addressed this in the generator project I made, so I'll consider this closed.
