### ISSUE TITLE
Is there an interpreter mode?

### ISSUE THREAD

**Issue by orangeagain** [RyanLamansky/dotnet-webassembly#28]
If there is an interpreter mode, we can run it on ios.
Is there an interpreter mode?

**Comment by RyanLamansky** [comment]
No interpretation is available at this time.

My plan for iOS is to provide a way to save the DLLs that this library produces; currently they exist only in memory, and although .NET Framework has this capability, it doesn't appear to be planned for conversion to .NET Core / 5+. This will give much better performance than interpretation and opens the door to full AoT compilation to native. No ETA on this but there are other open issues on that subject.
