### ISSUE TITLE
Easier API To Interact with Functions, Values and References

### ISSUE THREAD

**Issue by furesoft** [RyanLamansky/dotnet-webassembly#48]
I could make a PR with my current implementation.

It is much easier to export clr functions and values (structs) to a wasm module with attributes. Later I will implement to import values from wasm to a field

**Comment by RyanLamansky** [comment]
Would it be better for this to be an add-on library? This would give you full control over the release schedule.

**Comment by RyanLamansky** [comment]
As mentioned in my previous comment, I think this makes more sense to be an add-on library (via extension methods and other mechanisms) than being part of the base project, which is intended to be as small an plain as possible. Feel free to open an issue if there's something blocking you.
