### ISSUE TITLE
Does not run Doom

### ISSUE THREAD

**Issue by arontsang** [RyanLamansky/dotnet-webassembly#55]
For fun I tried to run Doom using dotnet-webassembly with Eric Sink's wasi implementation

https://github.com/arontsang/wasm-net-doom/tree/main

Would be cool if we could get this working.

Note, the version of Wasm Doom I included will generate a screen.data file which will act as the screen buffer

**Comment by RyanLamansky** [comment]
What error are you receiving?

**Comment by RyanLamansky** [comment]
Although this project should be capable of running the WebAssesmbly portions of the game, it's not enough. Satisfying the many external resources that need to be imported for things like graphics, sound, and input is out of scope for this project.

Another way of thinking about it is that this project only implements the "CPU". Other developers and projects will be needed to build the other parts of a complete system.
