### ISSUE TITLE
Get name of global variable

### ISSUE THREAD

**Issue by ghost** [RyanLamansky/dotnet-webassembly#64]
Given a Global variable instance(**WebAssembly.Global**), there doesn't seem to be an existing API to fetch the name of the GlobalVariable.

What's the best way to do this?

**Comment by RyanLamansky** [comment]
WebAssembly globals don't natively have names: they're accessed by sequential index number.  They can optionally be associated with imports and exports, which are a separate data structure that carries a name associated with the index.
